# Example services.yaml entry

# Service ID
find_unstaffed_flights:
  fields:
    start_date:
      selector:
        date:
    end_date:
      selector:
        date:
    aircraft_type:
      selector:
        select:
          options:
            - "73H"
            - "32N"
          custom_value: true
    role:
      selector:
        select:
          options:
            - "CDB"
            - "OPL"
            - "SUPT"
            - "INS"
            - "CC"
            - "CA"
            - "SUPC"
            - "SOL"
